---

# Train/val/test sets formatted as one of the following:
# 1) dir: path/to/imgs
# 2) file: path/to/imgs.txt
# 3) list: [path/to/imgs1, path/to/imgs2, ..]

path: ../data/mosquito_alert_2023
train: images/train
val: images/train
# test optional
test: images/test
# Classes
names:
  0: aegypti
  1: albopictus
  2: anopheles
  3: culex
  4: culiseta
  5: japonicus/koreicus
